name: Versum test CI
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  test:
    name: Versum test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
